using System.Threading;
using System.Threading.Tasks;
using UniversalBackup.LegacyImport.Models;

namespace UniversalBackup.LegacyImport.Services;

/// <summary>
/// Parses legacy backup structures (manifest.json or inventory.csv) generated by Universal-GameBackup.ps1.
/// </summary>
public interface ILegacyBackupParser
{
    /// <summary>
    /// Checks whether the specified folder contains a legacy backup set (manifest.json or inventory.csv).
    /// </summary>
    bool IsLegacyBackupFolder(string backupFolderPath);

    /// <summary>
    /// Parses the legacy backup folder, reading manifest.json (or falling back to inventory.csv),
    /// validating path containment, and verifying file/directory existence and sizes.
    /// </summary>
    Task<LegacyBackupManifest?> ParseAsync(string backupFolderPath, CancellationToken cancellationToken = default);
}
